name: release

on:
  push:
    tags: '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Publish release
       uses: goreleaser/goreleaser-action@v1
       with:
        version: latest
        args: release
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
