name: release

on:
  push:
    tags: '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

     - name: Publish release
       uses: goreleaser/goreleaser-action@v1
       with:
        version: latest
        args: release --release-notes=/tmp/release.txt
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
